export enum ApiErrorCodes {
    UNEXPECTED_ERROR = 600,
    JWT_TOKEN_INVALID = 511,
    JWT_NOT_FOUND = 513,
    JWT_TOKEN_EXPIRED = 599,
    UNKNOWN_ERROR_SHOW_TO_USER = 506,
    JWT_TOKEN_MISMATCH = 709,

    HMAC_SIGNATURE_INVALID = 611,
    HMAC_SIGNATURE_NOT_FOUND = 613,
    HMAC_SIGNATURE_MISMATCH = 809
}

export enum ApiErrorMessages {
    UNEXPECTED_ERROR = "Unexpected Error",
    JWT_TOKEN_EXPIRED = "Token Expired",
    JWT_TOKEN_INVALID = "Invalid Token",
    JWT_NOT_FOUND = "Token not found",
    JWT_TOKEN_MISMATCH = "TOKEN MISMATCH",

    HMAC_SIGNATURE_INVALID = "HMAC SIGNATURE INVALID",
    HMAC_SIGNATURE_NOT_FOUND = "HMAC SIGNATURE NOT FOUND",
    HMAC_SIGNATURE_MISMATCH = "HMAC SIGNATURE MISMATCH",

}